remote: origin
target-branch: main
chart-dirs:
- "deployments/helm"
helm-extra-args: "--timeout 600s"
chart-yaml-schema: ".github/configs/chart_schema.yaml"
validate-chart-schema: true
validate-chart-values: true
validate-maintainers: false
check-version-increment: true
validate-yaml: true
exclude-deprecated: true
